name: Release Action

on:
  push:
    tags:
      - pre-v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: 12.x
      - name: Compile TypeScript
        run: |
          npm ci
          npx tsc
        env:
          CI: true
      - uses: autosuite/autocommit@main
        with:
          commit-message: "Automatically updated uncompiled TS w/ compiled JS"
      - uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 0
      - run: git pull --rebase || echo "You are pushing a tag, not a branch."
      - uses: actions/setup-node@v1.1.2
        with:
          node-version: 12.x
      - name: Compile TypeScript
        run: |
          npm ci
          npx tsc
        env:
          CI: true
      - name: Self-Test
        uses: ./
      - uses: autosuite/autocommit@main
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  utility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: autosuite/automilestone@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
