name: Self-Test

on: [push]

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: autosuite/autoskip@master
        with:
          commit-filter: skip-log, skip-ci, automated
      - uses: autosuite/autobadge@0.1.0
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Compile TypeScript
        run: |
          npm ci
          npx tsc
        env:
          CI: true
      - name: Self-Test
        uses: ./
      - uses: autosuite/autolog@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
      - uses: autosuite/automilestone@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository: ${{ github.repository }}
          prefix: pre-
      - uses: autosuite/autocommit@master
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
